"""Build a portable, pre-rendered bilingual portfolio. Python standard library only."""
from pathlib import Path
import json
from html import escape
from hashlib import sha256

ROOT = Path(__file__).resolve().parent.parent
load = lambda name: json.loads((ROOT / 'content' / name).read_text())
profile = load('profile.json')
projects = sorted((p for p in load('projects.json') if p.get('visible', True)), key=lambda p: p['order'])
e = lambda value: escape(str(value), quote=True)

def t(en, ar, tag='span', cls=''):
    return f'<{tag}{f" class={chr(34)}{cls}{chr(34)}" if cls else ""} data-en="{e(en)}" data-ar="{e(ar)}">{e(en)}</{tag}>'

def arrow():
    return '<span class="arrow" aria-hidden="true">↗</span>'

def link(url, en, ar, cls='text-link', extra=''):
    return f'<a class="{cls}" href="{e(url)}" {extra}>{t(en, ar)}{arrow()}</a>'

def header(base):
    base = '../index.html' if base else ''
    nav = ''.join(link(base + '#' + anchor, en, ar, 'nav-link') for anchor, en, ar in [('work','Work','الأعمال'),('about','About','نبذة'),('experience','Experience','الخبرة')])
    return f'''<a class="skip-link" href="#main">{t('Skip to content','انتقل للمحتوى')}</a>
<header class="site-header"><div class="header-inner shell">
<a class="brand" href="{base}#top" aria-label="Hussein Abozina — home"><span class="brand-mark" aria-hidden="true">ha.</span><span>{t('Hussein Abozina','حسين أبوزينة')}<small>{t('MOBILE SOFTWARE ENGINEER','مهندس برمجيات موبايل')}</small></span></a>
<nav class="desktop-nav" aria-label="Main navigation">{nav}</nav>
<div class="header-actions"><button class="language-button" id="language-button" type="button" aria-label="Switch to Arabic" hidden>عربي</button>{link(profile['showroom'],'App showroom','معرض التطبيقات','showroom-nav')}<button id="menu-button" class="menu-button" type="button" aria-controls="mobile-menu" aria-expanded="false" aria-label="Open menu" hidden><span></span><span></span></button></div>
</div><nav id="mobile-menu" class="mobile-menu shell" aria-label="Mobile navigation" hidden>{nav}{link(base+'#capabilities','Capabilities','القدرات','nav-link')}{link(base+'#contact','Contact','تواصل','nav-link')}{link(profile['showroom'],'Visit app showroom','افتح معرض التطبيقات','nav-link')}</nav>
<noscript><nav class="no-script-nav shell">{nav}</nav></noscript></header>'''

def footer(base):
    base = '../index.html' if base else ''
    return f'''<footer class="site-footer shell"><a class="brand" href="{base}#top"><span class="brand-mark" aria-hidden="true">ha.</span>{t('Hussein Abozina','حسين أبوزينة')}</a><span>{t('Based in Egypt. Building for Android & iOS.','من مصر. أطور تطبيقات Android وiOS.')}</span><div>{link(profile['github'],'GitHub','GitHub')}{link(profile['showroom'],'App showroom','معرض التطبيقات')}</div><small>© 2026 Hussein Abozina</small></footer>'''

def shell(title, desc, body, base=''):
    version = sha256((ROOT/'assets/styles.css').read_bytes() + (ROOT/'assets/app.js').read_bytes()).hexdigest()[:10]
    schema = {'@context':'https://schema.org','@type':'Person','name':profile['name'],'jobTitle':'Mobile Software Engineer','email':'mailto:'+profile['email'],'sameAs':[profile['github'],profile['showroom']],'knowsAbout':['Flutter','Dart','iOS','Swift','SwiftUI','Android','Kotlin','Jetpack Compose','AI-Augmented Engineering'],'alumniOf':{'@type':'CollegeOrUniversity','name':'Mansoura University'}}
    return f'''<!doctype html>
<html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)}</title><meta name="description" content="{e(desc)}"><meta name="theme-color" content="#f7f5ef"><meta property="og:type" content="website"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta name="twitter:card" content="summary"><link rel="icon" href="{base}assets/favicon.svg"><link rel="preload" href="{base}assets/fonts/manrope-regular.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="{base}assets/styles.css?v={version}"><script src="{base}assets/app.js?v={version}" defer></script><script type="application/ld+json">{json.dumps(schema)}</script></head><body id="top">{header(base)}{body}{footer(base)}</body></html>'''

def screens(p, base='', hero=False):
    return ''.join(f'<img src="{base}{e(src)}" alt="{e(alt)}" width="{w}" height="{h}" loading="{"eager" if hero else "lazy"}" decoding="async">' for src, alt, w, h in [(s[0],s[1],900,1950) for s in p['screens']])

def card(p, index):
    return f'''<article class="project-card {p['slug']} {'project-feature' if index == 0 else ''}">
<div class="project-media"><div class="media-heading"><span>{t(*p['category'])}</span><span aria-hidden="true">0{index+1} / 03</span></div><a class="screen-pair" href="{e(p['url'])}" aria-label="Explore {e(p['name'])}">{screens(p)}</a><span class="media-caption">{t('Screens from the app','شاشات من التطبيق')}</span></div>
<div class="project-copy"><div class="project-heading"><h3>{e(p['name'])}</h3>{arrow()}</div>{t(*p['headline'],tag='p',cls='project-title')}{t(*p['description'],tag='p',cls='project-description')}{t(*p['contribution'],tag='p',cls='project-contribution')}{link(p['url'],'Explore '+p['name'],'استكشف '+p['name'],'project-link')}{t(*p['note'],tag='p',cls='project-note')}</div></article>'''

body = f'''<main id="main">
<section class="hero shell" aria-labelledby="hero-title"><div class="hero-copy">
<p class="eyebrow"><span class="status-dot" aria-hidden="true"></span>{t('Mobile Software Engineer','مهندس برمجيات موبايل')}</p>
<h1 id="hero-title">{t('Mobile software,','برمجيات موبايل،')}<br>{t('carefully built.','بعناية في كل تفصيلة.','em')}</h1>
{t('I turn product ideas into complete mobile experiences — bringing together thoughtful interfaces, solid architecture and reliable integrations, with ownership of the details that make the product work.','أحوّل أفكار المنتجات إلى تجارب موبايل متكاملة، تجمع واجهات مدروسة وهيكلة متينة وتكاملات موثوقة، مع مسؤولية عن التفاصيل اللي تخلّي المنتج يشتغل بكفاءة.','p','hero-description')}
<div class="hero-actions">{link(profile['showroom'],'Apps & Projects Showcase','استكشف معرض التطبيقات','button button-dark')}{link(profile['cv'],'Download CV','حمّل السيرة الذاتية','text-link','download')}</div>
<div class="hero-byline"><span dir="ltr">Flutter · iOS · Android</span><span aria-hidden="true">/</span>{t('Based in Egypt','مقيم في مصر')}</div></div>
<div class="hero-art"><div class="art-caption"><span class="tiny-cross" aria-hidden="true">✳</span>{t('Small screens. Complete experiences.','شاشات صغيرة. تجارب متكاملة.')}</div><div class="hero-screens"><a class="hero-screen first-screen" href="{profile['showroom']}projects/myshop/" aria-label="Explore MyShop"><img src="assets/images/myshop/home.webp" alt="MyShop storefront in the actual Flutter app" width="900" height="1950" fetchpriority="high"><span>MyShop <span aria-hidden="true">↗</span></span></a><a class="hero-screen second-screen" href="{profile['showroom']}projects/brees/" aria-label="Explore Brees"><img src="assets/images/brees/home_dashboard.webp" alt="Brees finance dashboard in the actual Flutter app" width="900" height="1950"><span>Brees <span aria-hidden="true">↗</span></span></a></div><div class="art-footer"><span>{t('Built with Flutter','طُوّرت بـFlutter')}</span><span class="mini-line" aria-hidden="true"></span><span>01—03</span></div></div></section>
<section class="proof-strip shell" aria-label="Experience at a glance"><div><strong>5</strong>{t('years with Flutter','سنوات مع Flutter')}</div><div><strong>20+</strong>{t('apps built or contributed to','تطبيقًا بنيته أو ساهمت فيه')}</div><div><strong>2+</strong>{t('years in a software company','سنة في شركة برمجيات')}</div><p>{t('Product detail. Engineering depth. Release responsibility.','اهتمام بالمنتج. عمق هندسي. مسؤولية الإطلاق.')}</p></section>
<section class="work-section shell" id="work"><div class="section-heading"><div><p class="eyebrow">{t('01 / Selected work','01 / أعمال مختارة')}</p><h2>{t('A few things','جزء من اللي')}<br>{t('I’ve been building.','ببنيه مؤخرًا.','em')}</h2></div><p>{t('A small selection of my Flutter engineering work. For the wider collection, contribution details, screenshots and demos, visit my separate Apps & Projects Showcase.','لمحة مختصرة من أعمالي الهندسية بـFlutter. المجموعة الأوسع، وتفاصيل مساهمتي، والشاشات والتجارب موجودة في معرض التطبيقات والمشاريع المستقل.')}</p></div><div class="projects-grid">{''.join(card(p,i) for i,p in enumerate(projects))}</div>
<a class="showroom-banner" href="{profile['showroom']}"><span class="banner-label">{t('APPS & PROJECTS SHOWCASE','معرض التطبيقات والمشاريع')}</span><span class="banner-title">{t('Explore the work. See the evidence.','استكشف الأعمال. شاهد التفاصيل.')}</span><span class="banner-detail">{t('Published apps, engineering projects, contributions & demos.','تطبيقات منشورة، مشاريع هندسية، مساهماتي وتجارب عملية.')}</span><span class="banner-arrow" aria-hidden="true">↗</span></a></section>
<section class="about-section shell" id="about"><div><p class="eyebrow">{t('02 / A little about me','02 / نبذة عني')}</p><h2>{t('Good interfaces.','واجهات مدروسة.')}<br>{t('Dependable foundations.','وأساس تقدر تعتمد عليه.','em')}</h2></div><div class="about-copy">{t('I’m Hussein, a Mobile Software Engineer. Flutter/Dart is my strongest specialization: 5 years of hands-on development and work across 20+ applications, including production apps, company and client work, and independent engineering projects.','أنا حسين، مهندس برمجيات موبايل. Flutter وDart هما أقوى تخصص عندي: خمس سنوات من التطوير العملي والعمل على أكثر من 20 تطبيقًا، بين تطبيقات فعلية وأعمال شركات وعملاء ومشاريع هندسية مستقلة.','p','lead')}{t('My hands-on native work includes Task Management Native: a substantial Swift/SwiftUI iOS implementation and an actively developing Kotlin/Jetpack Compose Android track. This complements my production Flutter background. I’ve also owned the custom backend on an end-to-end project.','خبرتي العملية في Native تشمل Task Management Native: تنفيذ iOS بـSwift وSwiftUI، ومسار Android بـKotlin وJetpack Compose ما زال قيد التطوير. الخبرة دي بتكمّل خلفيتي في تطبيقات Flutter الفعلية. وتولّيت أيضًا تطوير الباك إند المخصص لمشروع متكامل.','p')}{t('I use AI-Augmented Engineering throughout delivery: structure requirements and context, define acceptance criteria, anticipate implementation mistakes, review generated code, iterate and verify the result. Responsibility for the final implementation stays with me.','بستخدم AI-Augmented Engineering خلال التطوير: أنظّم المتطلبات والسياق، أحدد معايير القبول، أتوقع أخطاء التنفيذ، أراجع الكود المُولّد، وأحسّن التنفيذ وأتحقق من النتيجة. مسؤولية التنفيذ النهائي بتفضل عندي.','p')}<div class="about-links">{link(profile['cv'],'Read my CV','اقرأ سيرتي الذاتية','text-link','download')}{link(profile['github'],'Explore GitHub','شاهد GitHub')}</div></div></section>
<section class="experience-section shell" id="experience"><div class="section-heading compact"><div><p class="eyebrow">{t('03 / Experience','03 / الخبرة')}</p><h2>{t('The work behind the work.','الخبرة اللي وراء الشغل.')}</h2></div></div>
<div class="timeline"><article class="timeline-row"><div class="timeline-meta"><span class="timeline-dot" aria-hidden="true"></span>{t('May 2024 — Present','مايو 2024 — الآن')}<small>{t('Company experience','خبرة الشركات')}</small></div><div><h3>{t('Flutter Developer','مطور Flutter')}</h3><p class="employer">{t('Efadah Company for Software','شركة إفادة للبرمجيات')}</p>{t('Build and maintain Android and iOS apps across marketplace, delivery, booking and service products. Integrate APIs, payments, maps and notifications, and handle signing, store submissions, review fixes and post-release maintenance.','أبني وأصون تطبيقات Android وiOS في الأسواق والتوصيل والحجوزات والخدمات. أدمج APIs والمدفوعات والخرائط والإشعارات، وأتولى التوقيع والنشر على المتاجر ومعالجة المراجعات والصيانة بعد الإطلاق.','p')}</div></article>
<article class="timeline-row"><div class="timeline-meta"><span class="timeline-dot" aria-hidden="true"></span>{t('2021 — Present','2021 — الآن')}<small>{t('Independent development','تطوير مستقل')}</small></div><div><h3>{t('Independent & portfolio projects','مشاريع مستقلة ومشاريع عرض')}</h3><p class="employer">{t('Product exploration & engineering practice','استكشاف المنتجات وتطوير المهارات الهندسية')}</p>{t('Build Flutter showcases and hands-on native iOS and Android projects, with architecture, testing and CI workflows. Owned a custom backend for an end-to-end project. Use structured AI collaboration, code review and verification to refine implementations; the native Android track remains under active development.','أبني مشاريع عرض بـFlutter ومشاريع عملية بـNative iOS وAndroid، مع الهيكلة والاختبارات والتكامل المستمر. تولّيت باك إند مخصصًا لمشروع متكامل، وبستخدم تعاونًا منظمًا مع AI ومراجعة الكود والتحقق لتحسين التنفيذ. مسار Native Android ما زال قيد التطوير.','p')}</div></article></div>
<div class="credentials"><div><span class="eyebrow">{t('Education','التعليم')}</span><strong>{t('BSc Computer Science','بكالوريوس علوم الحاسب')}</strong><span>{t('Mansoura University · 2019–2022','جامعة المنصورة · 2019–2022')}</span></div><div><span class="eyebrow">{t('Languages','اللغات')}</span><strong>{t('Arabic & English','العربية والإنجليزية')}</strong><span>{t('Native Arabic · Professional working English','العربية لغة أم · الإنجليزية بمستوى عمل مهني')}</span></div></div></section>
<section class="capabilities-section shell" id="capabilities"><div class="section-heading compact"><div><p class="eyebrow">{t('04 / How I contribute','04 / ما أقدمه')}</p><h2>{t('Across the mobile lifecycle.','خلال دورة تطوير التطبيق.')}</h2></div></div><div class="capabilities-grid">
<article><span class="cap-number">01 /</span><h3>{t('Flutter & native mobile','Flutter وتطوير Native')}</h3>{t('Flutter/Dart is my core: production delivery, adaptive interfaces, motion and Arabic/English journeys. Hands-on native skills include Swift/SwiftUI for iOS and Kotlin/Jetpack Compose for Android, with the Android track in active development.','Flutter وDart هما الأساس: تسليم تطبيقات فعلية، واجهات متكيفة، حركة وتجارب بالعربية والإنجليزية. مهارات Native العملية تشمل Swift وSwiftUI لـiOS، وKotlin وJetpack Compose لـAndroid، ومسار Android قيد التطوير.','p')}<p class="skill-line">Flutter · Dart · Swift / SwiftUI · Kotlin / Jetpack Compose</p></article>
<article><span class="cap-number">02 /</span><h3>{t('Architecture & delivery','الهيكلة والتسليم')}</h3>{t('Maintainable features, state and API integrations, plus custom backend ownership on an end-to-end project. My Flutter delivery work includes payments, maps, notifications, debugging, unit/widget testing, CI/CD and App Store/Google Play releases.','ميزات وإدارة حالة وتكامل APIs قابلة للصيانة، مع ملكية باك إند مخصص لمشروع متكامل. شغلي في تسليم Flutter يشمل المدفوعات والخرائط والإشعارات وحل المشاكل واختبارات Unit وWidget وCI/CD والنشر على المتاجر.','p')}<p class="skill-line">BLoC / Cubit · Provider · Clean Architecture · REST · Firebase / Supabase · Testing · CI/CD</p></article>
<article><span class="cap-number">03 /</span><h3>{t('AI-Augmented Engineering','هندسة البرمجيات بمساعدة AI')}</h3>{t('Decompose requirements, design clear context and prompts, and define acceptance criteria. Anticipate likely AI implementation mistakes, review generated code, iterate on the implementation and verify the final result before accepting it.','أفكّك المتطلبات، أصمم سياقًا وطلبات واضحة، وأحدد معايير القبول. أتوقع أخطاء تنفيذ AI المحتملة، أراجع الكود المُولّد، أكرّر التحسين وأتحقق من النتيجة النهائية قبل قبولها.','p')}<p class="skill-line">{t('Requirements · Context & prompts · Acceptance criteria · Code review · Verification','المتطلبات · السياق والطلبات · معايير القبول · مراجعة الكود · التحقق')}</p></article></div></section>
<section class="contact-section shell" id="contact"><div class="contact-panel"><div><p class="eyebrow">{t('HAVE A PRODUCT IN MIND?','عندك فكرة منتج؟')}</p><h2>{t('Let’s build','خلّينا نبني')}<br>{t('something useful.','حاجة مفيدة.','em')}</h2>{t('For mobile development, team collaboration and engineering opportunities.','لتطوير تطبيقات الموبايل والتعاون مع الفرق وفرص العمل الهندسي.','p')}</div><div class="contact-links"><a class="email-link" href="mailto:{profile['email']}" dir="ltr">{profile['email']}{arrow()}</a>{link(profile['cv'],'Download CV','حمّل السيرة الذاتية','text-link','download')}{link(profile['github'],'GitHub','GitHub','text-link')}{link(profile['showroom'],'Visit the app showroom','افتح معرض التطبيقات','text-link')}</div></div></section></main>'''
(ROOT/'index.html').write_text(shell('Hussein Abozina — Mobile Software Engineer | Flutter · iOS · Android', 'Mobile Software Engineer. Flutter/Dart core specialization, 5 years and 20+ apps; hands-on Swift/SwiftUI, Kotlin/Compose and AI-Augmented Engineering. Explore my Apps & Projects Showcase.', body))

# Preserve original shared URLs, with the same new navigation and visual system.
earlier = load('earlier-projects.json')
for p in earlier:
    gallery = ''.join(f'<figure><a href="../assets/images/{e(src)}" target="_blank" rel="noopener"><img src="../assets/images/{e(src)}" alt="{e(alt)}" width="450" height="975" loading="lazy"></a><figcaption>{e(alt)}</figcaption></figure>' for src,alt in p['images'])
    sections = ''.join(f'<article>{t(en[0],ar[0],"h2")}{t(en[1],ar[1],"p")}</article>' for en,ar in zip(p['sections_en'][:3],p['sections_ar'][:3]))
    boundary = t('Original Flutter delivery; later product changes belong to another team. These images are the supplied portfolio materials.','تطوير نسخة Flutter الأصلية؛ التحديثات اللاحقة نفذها فريق آخر. الصور من ملفات البورتفوليو المرفقة.','p','archive-note') if p['id']=='overdeal' else ''
    case = f'''<main id="main" class="case-page shell">{link('../index.html#work','Back to selected work','العودة للأعمال المختارة','text-link')}<section class="case-intro"><p class="eyebrow">{t('EARLIER WORK / '+p['type_en'],'أعمال سابقة / '+p['type_ar'])}</p><h1>{e(p['title'])}</h1>{t(p['desc_en'],p['desc_ar'],'p','lead')}{boundary}{link(profile['showroom'],'Explore the latest app collection','شاهد أحدث مجموعة تطبيقات','button button-dark')}</section><section class="case-gallery" aria-label="Project screenshots">{gallery}</section><section class="case-notes">{sections}</section><div class="case-end">{link('../index.html#contact','Talk about a mobile project','تواصل بخصوص مشروع موبايل','button button-dark')}</div></main>'''
    (ROOT/'projects'/p['file']).write_text(shell(p['title']+' — Hussein Abozina',p['desc_en'],case,'../'))
print(f'Built portfolio with {len(projects)} selected projects and {len(earlier)} preserved case-study routes.')
